#!/bin/sh
touch_sensor=/dev/etx_device
echo "INICICIANDO DRIVER"
while true
do
    button=`cat $touch_sensor`
    if [ $button -ne "0" ]
    then
        echo "PRESIONADO EL BOTON"
        sleep 2
    fi
done
